### ISSUE TITLE
The mdl-datepicker don't show 31 december correctly

### ISSUE THREAD

**Issue by 1jGabriel** [mseemann/angular2-mdl-ext#1169]
The component don't show 31 december 2018.

![capturar](https://user-images.githubusercontent.com/26119703/33036676-e44ee8e2-ce0d-11e7-81d7-40544ba92236.PNG)

**Comment by mseemann** [comment]
published as `@angular-mdl/datepicker:0.0.4`

**Comment by 1jGabriel** [comment]
Thanks.
