### ISSUE TITLE
Tried to implement select but display error

### ISSUE THREAD

**Issue by akhilsahu** [mseemann/angular2-mdl-ext#1262]
I tried importing import { MdlSelectModule } from '@angular-mdl/select';
and adding to imports in app.module.ts but displays error. 
`ERROR in ./node_modules/@angular-mdl/popover/popover.js
Module not found: Error: Can't resolve '@angular-mdl/core' in 'C:\project\angutestpro\great-market\node_modules\@angular-mdl\popover'
resolve '@angular-mdl/core' in 'C:\project\angutestpro\great-market\node_modules\@angular-mdl\popover'
  Parsed request is a module
  using description file: C:\project\angutestpro\great-market\node_modules\@angular-mdl\popover\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\project\angutestpro\great-market\node_modules\@angular-mdl\popover\package.json (relative path: .)
    resolve as module
      C:\project\angutestpro\great-market\node_modules\@angular-mdl\popover\node_modules doesn't exist or is not a directory
      C:\project\angutestpro\great-market\node_modules\@angular-mdl\node_modules doesn't exist or is not a directory`

**Comment by akhilsahu** [comment]
Is there a plunkr demo for this . So I can understand better how to integrate

**Comment by mseemann** [comment]
https://github.com/mseemann/angular-mdl-a4-angular-cli

ERROR in ./node_modules/@angular-mdl/popover/popover.js **Module not found**: Error: Can't resolve '**`@angular-mdl/core`**'
