### ISSUE TITLE
mdl-select dropdown items always displayed

### ISSUE THREAD

**Issue by LukeHartcher** [mseemann/angular2-mdl-ext#128]
Setting up a simple mdl-select (as per sample) and the dropdown is always displayed and the down arrow is located underneath the text area and not to the right.

```
<mdl-select *ngFor="let f of filters" [(ngModel)]="selectedFilters" multiple="true" placeholder="Select {{f.name}}">
    <mdl-option *ngFor="let v of f.values" [value]="v.id">{{v.name}}</mdl-option>
</mdl-select>
```

![image](https://cloud.githubusercontent.com/assets/1154551/20686269/18032042-b60c-11e6-887a-03f88cae3aaf.png)

Even if I copy/paste the sample app code from github it still renders incorrectly.

Or am I doing something wrong?

**Comment by mseemann** [comment]
the ext components need special scss imports: @import '~@angular2-mdl-ext/select/select'; the original css from getmdl.io is not sufficient. Did you add these scss files?

**Comment by LukeHartcher** [comment]
Ok thanks, will add scss import.

**Comment by LukeHartcher** [comment]
I added "@import '~@angular2-mdl-ext/select/select';" to my styles.scss (am using latest angular-cli with webpack) but still getting an issue. The arrow is now correctly positioned but the dropdown is still always displayed:

![image](https://cloud.githubusercontent.com/assets/1154551/20690005/25fc8908-b61c-11e6-8c28-b4b12ee33067.png)

**Comment by LukeHartcher** [comment]
Fixed! I imported the popover also and it now works.
Sorry , should have read the README better..

**Comment by gcphost** [comment]
I also needed to include popover:
`@import '~@angular2-mdl-ext/select/select';
@import '~@angular2-mdl-ext/popover/popover';`
