### ISSUE TITLE
Select with autocomplete

### ISSUE THREAD

**Issue by leolorenzoluis** [mseemann/angular2-mdl-ext#129]
Select with autocomplete.

**Comment by kononenko-a-m** [comment]
is there any work done for this functionality?

**Comment by mseemann** [comment]
not at all!

**Comment by kononenko-a-m** [comment]
I've added PR https://github.com/mseemann/angular2-mdl-ext/pull/397 @mseemann can you please review?

**Comment by kononenko-a-m** [comment]
@mseemann I've updated PR, can you please take a look into it?

**Comment by mseemann** [comment]
published as  @angular2-mdl-ext/select:0.10.0
