### ISSUE TITLE
http://mseemann.io/angular2-mdl-ext/select example code?

### ISSUE THREAD

**Issue by clockworked247** [mseemann/angular2-mdl-ext#1335]
Hi there, I'm attempting to use the select autocomplete feature and am having trouble.  I would love to see the implementation of the line:

`matchSorter:'name':autocompleteSelect.searchQuery`

for reference purposes.  Would it be possible to surface the implementation of this page as a part of the docs or create a sandbox that illustrates the implementation more clearly?  

Thank you!

**Comment by mseemann** [comment]
hi,

the sources: https://github.com/mseemann/angular2-mdl-ext/blob/af2c97515eaff9d360372ed8c1a0d1d992c42013/src/e2e-app/app/select/matchSorter.pipe.ts

the implementation is part of this repo. pls see the aforementioned link.

**Comment by clockworked247** [comment]
Great, thanks @mseemann
