### ISSUE TITLE
popover does not hide when I click outside

### ISSUE THREAD

**Issue by maku** [mseemann/angular2-mdl-ext#25]
I try to use mdl-popover. 
When the popover is shown it does not hide when I click outside the popover area. 
(only when I explicit call the toggle method)

**Comment by mseemann** [comment]
@tb please have a look.

**Comment by tb** [comment]
It works for me.

@maku, is it possible possible that some component that wrap popover does `$event.stopPropagation();` and click never gets down to this [callback](https://github.com/mseemann/angular2-mdl-ext/blob/master/src/components/popover/popover.ts#L42)?

**Comment by nikoTM** [comment]
@tb can it be related to the fact that global listeners are not removed on ngOnDestroy somehow?

**Comment by tb** [comment]
Please see https://github.com/mseemann/angular2-mdl-ext/pull/29

I added test for popup hide and ngOnDestroy global listeners remove @nikoTM mentioned.

**Comment by maku** [comment]
@tb it seems the problem depends on the change detection mechanism. When I remove changeDetection: ChangeDetectionStrategy.OnPush also the hiding works...
