### ISSUE TITLE
Feature Request: Expansion Panel

### ISSUE THREAD

**Issue by shootdaj** [mseemann/angular2-mdl-ext#35]
Specification given here: 

https://material.google.com/components/expansion-panels.html#

Continued from https://github.com/mseemann/angular2-mdl/issues/116

**Comment by abdulqadir93** [comment]
@mseemann Can I claim this one? I'd like to work on this one.

**Comment by mseemann** [comment]
Yes. Please!

**Comment by mseemann** [comment]
@abdulqadir93 thx a lot! the package is now released and the demo is available. If you have update for your component please create a pr and increase the version number in the package.json file.

**Comment by mseemann** [comment]
@abdulqadir93 I have updated the master to be compatible with angular4. It looks ok but it seems the auto height calculation for the expansion panel is no longer working. can you take a look what's wrong there? thx a lot!

**Comment by mseemann** [comment]
@abdulqadir93 it would also be great if you could checkout this https://github.com/mseemann/angular2-mdl-ext/issues/483 issue.
