### ISSUE TITLE
Peer dependency on Popover@0.2.0

### ISSUE THREAD

**Issue by nikoTM** [mseemann/angular2-mdl-ext#37]
Popover [requires](https://github.com/mseemann/angular2-mdl-ext/blob/master/src/components/popover/package.json#L22) peer dependency of exact version of angular2-mdl@1.7.1 resulting in this: 

```
some-project@0.0.1
├── @angular2-mdl-ext/popover@0.2.0 
├── @angular2-mdl-ext/select@0.2.0 
└── UNMET PEER DEPENDENCY angular2-mdl@1.8.1

```
Am I missing something here, or package.json needs to be updated ?

**Comment by mseemann** [comment]
yep. fixed in @angular2-mdl-ext/popover@0.2.1
