### ISSUE TITLE
BrowserModule is imported into Select Component

### ISSUE THREAD

**Issue by nikoTM** [mseemann/angular2-mdl-ext#38]
What is the need for BrowserModule being [imported](https://github.com/mseemann/angular2-mdl-ext/blob/master/src/components/select/select.ts#L151) ? Please use CommonModule so the component can be used in lazy loaded modules, rather than top level module.

**Comment by tb** [comment]
Ill fix it

**Comment by nikoTM** [comment]
@tb might want to confirm that with @mseemann, I might be misunderstanding something, but I think it needs to be CommonModule.

**Comment by tb** [comment]
It should be CommonModule, I provided link to FAQ in commit.

**Comment by mseemann** [comment]
npm version 0.2.1
