### ISSUE TITLE
Visual issues on Select component

### ISSUE THREAD

**Issue by nikoTM** [mseemann/angular2-mdl-ext#39]
1. Component's height ignores being out of view. A possible solution might be to check available height via JS. But issue is fixable on users' end, using custom css. ( As a side issue, you have !important [here](https://github.com/mseemann/angular2-mdl-ext/blob/master/src/components/select/select.scss#L37), which seems to be unnecessary, and forces user to use !important as well)
![localhost-8100-dashboard-meals](https://cloud.githubusercontent.com/assets/1929832/19001410/b7b4ad9a-874f-11e6-9d3e-58521c81b583.png)

2. Text overflow is ignored when select is focused and options list is closed as seen here: 
![screenshot from 2016-09-30 20 48 21](https://cloud.githubusercontent.com/assets/1929832/19001643/e23138bc-8750-11e6-824e-42ec87ff73ce.png)

**Comment by tb** [comment]
@nikoTM Please check latest release popover@0.2.2 and select@0.2.2

The !important is removed and the text overflow is fixed.

I dont think this fully addressed the first point. What would be nice is to have popover above the input (which is possible when mdl-popover has `bottom: 22px;`) however I was not able to come up with good way to toggle this properly based on position and preserve proper behaviour. Here is some code I tried in popover:

    private show(event: Event) {
        event.stopPropagation();
        this.updateDirection(event);
        this.isVisible = true;
    }

    private updateDirection(event: Event) {
        const parentRect = document.body.getBoundingClientRect();
        const targetRect = (<HTMLElement>event.target).getBoundingClientRect();
        const targetHeight = (<HTMLElement>event.target).offsetHeight;
        const height = this.elementRef.nativeElement.offsetHeight;

        const bounds = {
            top: 0,
            bottom: parentRect.height,
        };
        const spaceAvailable = {
            top: targetRect.top - bounds.top,
            bottom: bounds.bottom - (targetRect.top + targetRect.height)
        };

        this.directionUp = spaceAvailable.bottom < height;

        console.log('spaceAvailable', spaceAvailable);
        console.log('height', height);
        console.log('targetHeight', targetHeight);
        console.log('this.directionUp', this.directionUp);
    }

On top of that offsetHeight does not work with mdl-popover `display: none;`, but when its `visibility: hidden;` the is issue with invisible div expanding the view.

**Comment by nikoTM** [comment]
@tb so I have looked into it. This partially solves the issue 

```TypeScript
private show(event: Event) {
        event.stopPropagation();
        this.isVisible = true;
        setTimeout(() => {
          this.updateDirection(event);
        }, 10);
    }

    private updateDirection(event: Event) {
      const nativeEl = this.elementRef.nativeElement;
      const targetRect = (<HTMLElement>event.target).getBoundingClientRect();
      const viewHeight = window.innerHeight;
      const height = nativeEl.offsetHeight;


      const spaceAvailable = {
          top: viewHeight - targetRect.top,
          bottom: viewHeight - targetRect.bottom
      };

      this.directionUp = spaceAvailable.bottom < height;

    }
```

Things that need to be improved here:
1. setTimeout is not reliable(on slower machines angular can take longer to digest the change, so we will end up with height 0), also causes a minor flicker. This can be solved for static popovers, by storing the height value, but those with dynamic height will still struggle. 
2. We are not handling scenarios where available space on both sides is lower than height. I think we need something like:

```TypeScript
let absoluteHeight = Math.max(spaceAvailable.top, spaceAvailable.bottom);
if( absoluteHeight < height) {
 nativeEl.style.maxHeight = absoluteHeight;
} else if(spaceAvailable.bottom < height) {
 this.directionUp = true;
}
```
And probably remove maxHeight on hide.

**Comment by tb** [comment]
@nikoTM could you check if the setTimeout can be fixed using `this.changeDetectionRef.markForCheck();` like [here](https://github.com/mseemann/angular2-mdl-ext/commit/2b185d5bc3c031b5a6e0a91d6fb4a54d8b16fdb4#diff-722b1f04427a2759ba6c50300fabfa94R67)?

Can you also make a branch with this code so that I can checkout it :)

**Comment by nikoTM** [comment]
@tb sorry for the delay, I will try to make the branch today.
