### ISSUE TITLE
Getting error for missing $popover-direction-up-bottom-offset variable

### ISSUE THREAD

**Issue by leifwells** [mseemann/angular2-mdl-ext#501]
I installed `@angular2-mdl-ext` yesterday and received an error that there was a missing variable `$popover-direction-up-bottom-offset`.

I added the `$popover-direction-up-bottom-offset: 20px;` to my `styles.scss` file to make the error go away. Everything is working now. Have I missed something?

**Comment by mseemann** [comment]
$popover-direction-up-bottom-offset is defined in src/components/popover/popover.scss. Did you include it? like: https://github.com/mseemann/a2-mdl-webpack/blob/master/src/styles.scss

**Comment by leifwells** [comment]
Here is a clip of my `styles.scss` per documentation with the added var:
```
@import "~angular2-mdl/scss/color-definitions";

$color-primary: $palette-blue-500;
$color-primary-dark: $palette-blue-700;
$color-accent: $palette-amber-A200;
$color-primary-contrast: $color-dark-contrast;
$color-accent-contrast: $color-dark-contrast;
// THIS VAR DUE TO ERROR
$popover-direction-up-bottom-offset: 20px;

@import '~angular2-mdl/scss/material-design-lite';
@import '~@angular2-mdl-ext/popover/popover';
@import '~@angular2-mdl-ext/select/select';
```

**Comment by mseemann** [comment]
ok. i see. the popover package wan't published. done..
