### ISSUE TITLE
[Expansion Panel] ngFor not working as expected

### ISSUE THREAD

**Issue by richardsengers** [mseemann/angular2-mdl-ext#581]
I'm using the expansion panel with an *ngFor loop
 
<mdl-expansion-panel-group #panelGroup>
  <mdl-expansion-panel *ngFor="let user of users; let i = index">
    ...
  </mdl-expansion-panel>
</mdl-expansion-panel-group>

The toggles now work seperately from each other. So panel 1 does not collapse panel 2 when it is expanded etc

For example 
<button (click)="panelGroup.getPanel(0).toggle()">Toggle 1</button
will expand and collapse the first panel, but it does nothing with a second or third panel

**Comment by mseemann** [comment]
please provide a plnkr that demosntrates your problem.

**Comment by mseemann** [comment]
no input since 8 days. can be reopened if needed.

**Comment by richardsengers** [comment]
Sorry for the delay.
I think I have to refactor my code since a simple plunker works just fine
https://plnkr.co/edit/a7eQ7g1LPpmNX3lRUJ3O?p=preview

This issue can be closed indead.

**Comment by mseemann** [comment]
👍
