### ISSUE TITLE
ReferenceError: Event is not defined on angular universal

### ISSUE THREAD

**Issue by ozknemoy** [mseemann/angular2-mdl-ext#616]
after importing select@0.10.3 inside my angular server side render 4.0.1 project i have "ReferenceError: Event is not defined" on node server
>  __metadata('design:paramtypes', [Event])
in this snippet
__decorate$2([
        _angular_core.HostListener('document:click', ['$event']), 
        __metadata$2('design:type', Function), 
        __metadata$2('design:paramtypes', [Event]), 
        __metadata$2('design:returntype', void 0)
    ], MdlPopoverComponent.prototype, "onDocumentClick", null);

after i commented this code new error popup: KeyboardEvent is not defined  __metadata('design:paramtypes', [KeyboardEvent]),

on client side render angular 2.4 it works fine

**Comment by mseemann** [comment]
universal is not supported. if you need this feature you can provide a pr.

**Comment by jirungaray** [comment]
@mseemann are there any plans to support SSR?

**Comment by marknaber** [comment]
Has there been any progress on this for Universal? Are there any further extensions to MDL that support Universal (if not)?
