### ISSUE TITLE
MdlExpansionPanelModule Imports BrowserModule

### ISSUE THREAD

**Issue by racerhere** [mseemann/angular2-mdl-ext#617]
* Clone project [https://github.com/racerhere/test-angular-mdl](https://github.com/racerhere/test-angular-mdl)
* `npm install`
* Go to `http://localhost:4200/eager`. Everything works when modules are eagerly loaded.
* Go to `http://localhost:4200/lazy`. See console for

>  Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

* Comment the import of MdlExpansionPanelModule in src\app\shared\shared.module.ts (lines 8 and 19).
* Go to `http://localhost:4200/lazy`. Works fine now.

**Comment by racerhere** [comment]
@mseemann Please take a look at the discussion here [https://github.com/angular/angular/issues/15579](https://github.com/angular/angular/issues/15579). I cannot import animations in a shared module. Closing the issue now.
Thanks,
@racerhere

**Comment by mseemann** [comment]
👍
