### ISSUE TITLE
Unable to install angular2-mdl-ext for Angular 2.2.4

### ISSUE THREAD

**Issue by mmgyce** [mseemann/angular2-mdl-ext#620]
I'm getting the following error /node_modules/@angular-mdl/expansion-panel/expansion-panel.component.ts (20,38): Cannot find module '@angular/platform-browser/ani
mations'.) 

I think this is because is targeting Angular 4.

I don't know how to install a package version for Angular 2.2.4

**Comment by mseemann** [comment]
which version did you add to yor package.json?

**Comment by mmgyce** [comment]
"@angular-mdl/expansion-panel": "0.0.4"

**Comment by mseemann** [comment]
this is the version for angular4. if you are lookibng for a version that is compatible with angular 2 you need to install angular2-mdl-ext/expansion-panel. see the README:

> The master supports angular 4. If you are looking for an angular 2 compatible version please refer to this branch: https://github.com/mseemann/angular2-mdl-ext/tree/angular2
