### ISSUE TITLE
Angular 4 Select is always in open mode

### ISSUE THREAD

**Issue by phystem** [mseemann/angular2-mdl-ext#624]
I'm using latest angular 4 with mdl select and I used the code given in the demo . And it is behaving like this

![image](https://cloud.githubusercontent.com/assets/11405204/24831105/09f10a12-1cb1-11e7-9023-1326d7de176a.png)

**Comment by mseemann** [comment]
did you include the scss for select?

**Comment by phystem** [comment]
Importing did the trick

I'm not using scss, but using css.
Anyhow I imported the css using 
```
@import '../node_modules/@angular-mdl/select/select.css';
@import '../node_modules/@angular-mdl/popover/popover.css';
```

You can add this as part of demo site as well
