### ISSUE TITLE
[Select] Error in more recent version of Angular2

### ISSUE THREAD

**Issue by castrolol** [mseemann/angular2-mdl-ext#72]
I get the error  `Can't construct a query for the property "optionComponents" of "MdlSelectComponent" since the query selector wasn't defined.` when I try to use the select component.

My code is:
```html
    <mdl-select [(ngModel)]="heroId">
        <mdl-option *ngFor="let h of heroes" [value]="h.id">{{h.name}}</mdl-option>
    </mdl-select>
```

The code is very similar to the sample in docs, I think the problem is the update in Angular2.

**Comment by tb** [comment]
@castrolol I Installed angular 2.1.1 in  angular2-mdl-ext and `npm start`ed. No such error.

**Comment by nikoTM** [comment]
@tb, happens for me as well, on `angular-cli@1.0.0-beta18`  solved by changing imports here:
```Typescript
import { MdlPopoverModule, MdlPopoverComponent } from '../popover/index';
import { MdlOptionComponent } from './index';
```
to: 
```Typescript
import { MdlPopoverModule, MdlPopoverComponent } from '../popover/popover';
import { MdlOptionComponent } from './option';
```

**Comment by castrolol** [comment]
@nikoTM thank you I'll try

**Comment by nikoTM** [comment]
@castrolol new version is already merged, just install select component again.

**Comment by mseemann** [comment]
Seems to be fixed...
