### ISSUE TITLE
Not able to close angular2-mdl-ext/expansion-panel

### ISSUE THREAD

**Issue by kumbharkar-amit** [mseemann/angular2-mdl-ext#739]
Hello team,

I am referring the single panel expansion example from [here](http://mseemann.io/angular2-mdl-ext/expansion-panel), but I am not able to close or toggle the expansion panel. Following is my HTML code:

`      <mdl-expansion-panel>
        <mdl-expansion-panel-header>
          <mdl-expansion-panel-header-list-content>Primary Title</mdl-expansion-panel-header-list-content>
          <mdl-expansion-panel-header-secondary-content>Secondary value</mdl-expansion-panel-header-secondary-content>
        </mdl-expansion-panel-header>
        <mdl-expansion-panel-content>
          <mdl-expansion-panel-body>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
              standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to
              make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
              remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
              Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions
              of Lorem Ipsum.</p>
          </mdl-expansion-panel-body>
          <mdl-expansion-panel-footer>
            <mdl-button>Cancel</mdl-button>
            <mdl-button>Save</mdl-button>
          </mdl-expansion-panel-footer>
        </mdl-expansion-panel-content>
      </mdl-expansion-panel>`

This is the exact code copied from the above [url](http://mseemann.io/angular2-mdl-ext/expansion-panel).

**Comment by mseemann** [comment]
did you also include the css?
