### ISSUE TITLE
Please push up new version to NPM

### ISSUE THREAD

**Issue by JSMike** [mseemann/angular2-mdl-ext#771]
Hi :)

[You made a change a few days ago,](https://github.com/mseemann/angular2-mdl-ext/commit/95ccef5a5f89d5944c3e5d9c5bc44c2418d6b744) this change resolves an error that appears when lazy loading a module that includes expansion panels. Could you please push up a new version to NPM?

**Comment by mseemann** [comment]
ups :) done.

**Comment by JSMike** [comment]
Thank you :)
