### ISSUE TITLE
Bug: Select Component initial value is not displayed properly when using reactive forms

### ISSUE THREAD

**Issue by rbj325** [mseemann/angular2-mdl-ext#81]
I tried to create a plunk with a minimal reproduction but could not find any public deploys of this repository:

http://plnkr.co/edit/6crj2W

The use case is, I have a component that is pulling in data, creating child components and passing in populated forms.  I see that the initial value is working fine using static forms so I'm not 100% sure this isn't something I'm doing wrong either.

**Comment by mseemann** [comment]
@rbj325  i have updated the plnkr (http://plnkr.co/edit/56LV31gPDgVQftw3obyA?p=preview) with the required system.js configuration. can you check this.

**Comment by rbj325** [comment]
Thanks!  I have it working now minus the CSS.  It's not reproducing my issue though so I will double check my code and see if I can get it to reproduce the issue(or find the problem in my code).

http://plnkr.co/edit/mBL0fQFHTRN8kojANmCs

**Comment by rbj325** [comment]
I have not been able to reproduce it so I'm going to go with it's an issue in my code.  I will close this until I am able to reproduce it for you.

**Comment by mseemann** [comment]
👍

**Comment by rbj325** [comment]
@mseemann Just to loop you into what I found, it turned out in my code there was a race condition in retrieving data from a HTTP service and the way I am rendering the form using dynamic components.  I'm not sure if there is anything you can do on your end to "fix" this situation but I am looking into re-structuring my code to avoid the race condition.

Here is an updated plunk that is closer to what I am describing but I could not manually introduce the race condition using setTimeout and could not get rxjs loaded properly:

http://plnkr.co/edit/vcxAVaKhGIaWLk2pSXe7?p=preview

Not sure if it's worth looking into yet but I will loop back with my solution when I figure it out.

**Comment by rbj325** [comment]
Looping back here, I ended up resolving this by restructuring my code to pass the values in instead of grabbing the values from a service.
