### ISSUE TITLE
mdl-select error when changing select IE11

### ISSUE THREAD

**Issue by snimelius** [mseemann/angular2-mdl-ext#846]
**IE11**
I have multiple mdl-select elements for filtering. When I want to select from a different mdl-select while one is open "ERROR TypeError: Object doesn't support this action" is being thrown in IE11.
The same behaviour is on the documentation page. Any ideas how to get around this?

**Comment by mseemann** [comment]
fixed by https://github.com/mseemann/angular2-mdl-ext/pull/940
