### ISSUE TITLE
[MDL-SELECT] Drop down list is always visible

### ISSUE THREAD

**Issue by waiholiu** [mseemann/angular2-mdl-ext#933]
When put into solution, the drop down list is always visible.

This is the code I used and I have attached a file showing what it looks like.
```
<mdl-select placeholder="testing">
    <mdl-option [value]="1">option1</mdl-option>
    <mdl-option [value]="2">option2</mdl-option>
</mdl-select>
```

![image](https://user-images.githubusercontent.com/8047097/28489200-3a37ad7e-6f00-11e7-924f-f9ad20a4b542.png)

I also created a sample project which demonstrates the problem at https://github.com/waiholiu/testMdlSelect/blob/master/src/app/app.component.html. Project is generated using angular cli so you can simply run it with ng serve.

Not sure if this is a bug or I have set up the project wrong.

**Comment by jirungaray** [comment]
looks like you are missing the required CSS files, make sure you are including all CSS (or SCSS) mentioned on https://github.com/mseemann/angular2-mdl-ext

**Comment by phystem** [comment]
Already mentioned in #624
