### ISSUE TITLE
DatePicker - Ok and Cancel

### ISSUE THREAD

**Issue by Dadarkp3** [mseemann/angular2-mdl-ext#995]
I don't know if you can help, but I'm using the date-picker and need to call a different dialog when the user clicks ok, how can I do that with this component?

**Comment by mseemann** [comment]
have a look at the demo code:
https://github.com/mseemann/angular2-mdl-ext/blob/a7748ecfe700105b174d37023942750dfcb643ef/src/e2e-app/app/datepicker/datepicker.component.ts#L21

you just need to open your dialog at this line.
